{% set pyproject = load_file_data('pyproject.toml') %}
{% set description = pyproject.get('project').get('description') %}
{% set home = pyproject.get('project', {}).get('urls').get('Homepage') %}

{% set major = load_file_regex(
  load_file="src/oawidgets/version.py",
  regex_pattern='MAJOR = (.+)') %}
{% set minor = load_file_regex(
  load_file="src/oawidgets/version.py",
  regex_pattern='MINOR = (.+)') %}
{% set post = load_file_regex(
  load_file="src/oawidgets/version.py",
  regex_pattern='POST = (.+)') %}

{% set version = major[1]+'.'+minor[1]+'.'+post[1] %}

package:
  name: oawidgets
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 2
  script: {{PYTHON}} -m pip install .

requirements:
  build:
      - python {{PY_VER}}
      - setuptools
  run:
      - python  >=3.6
      - ipython
      - openalea.mtg
      - k3d
      - pyvis
      - matplotlib

about:
  home: {{ version }}
  license: CeCILL_C
  summary: {{ home }}
