{% set data = load_setup_py_data() %}

package:
  name: oawidgets
  version: {{ data.get('version') }}

source:
  path: ..

build:
  noarch: python
  preserve_egg_dir: True
  number: 2
  script: {{PYTHON}} setup.py install #--single-version-externally-managed --record=record.txt

requirements:
  build:
      - python {{PY_VER}}
      - setuptools
  run:
      - python  >=3.6
      - ipython
      - openalea.mtg
      - k3d
      - pyvis
      - matplotlib

about:
  home: http://openalea.rtfd.io/
  license: CeCILL_C
  summary: oawidgets provides Jupyter widgets for MTG and 3D visualization as well as lpy

