name: oawidgets
channels:
  - openalea3
  - conda-forge
dependencies:
  - python  >=3.6
  - openalea.mtg
  - openalea.deploy
  - openalea.hydroshoot
  - openalea.lpy
  - k3d
  - pyvis
  - matplotlib
  - pip
  - pip:
      - -e ..[doc]
