name: Building and publish package using anaconda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-and-publish:
    name: ${{ matrix.os }}, Python 3.${{ matrix.python-minor-version }} for conda deployment
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ ubuntu-latest , macos-latest , windows-latest]
        python-minor-version: [7, 8, 9]

    steps:
    - uses: actions/checkout@v3
    - name: Build and Publish
      uses: openalea/action-build-publish-anaconda@v0.1.0
      with:
        conda: conda
        python: ${{ matrix.python-minor-version }}
        channels: openalea3, openalea, conda-forge
        token: ${{ secrets.ANACONDA_TOKEN }}